[project]
name = "checkin"
description = "Daily checkin rewards system"
authors = []
telemetry = true
cache_dir = "./.clarinet/cache"
requirements = []

[contracts.monday]
path = "contracts/monday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.tuesday]
path = "contracts/tuesday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.wednesday]
path = "contracts/wednesday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.thursday]
path = "contracts/thursday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.friday]
path = "contracts/friday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.saturday]
path = "contracts/saturday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.sunday]
path = "contracts/sunday.clar"
clarity_version = 3
epoch = "3.0"

[contracts.checkin]
path = "contracts/checkin.clar"
clarity_version = 3
epoch = "3.0"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = "https://api.hiro.so"
